name: timegeo
channels:
  - conda-forge
  - defaults
dependencies:
  - powerlaw=1.5
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libcxx=19.1.7
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - py4j==0.10.9.7
      - pyspark==3.5.4
prefix: /Users/chris/anaconda3/envs/pyspark-scala2.13
